# Configuration file for the log monitoring application
port: 8008
auth:
  enabled: true
  username: "admin"
  password: "loged123"
log_files:
  - name: "Sample Log"
    path: "./src/sample.log"
  - name: "System Log"
    path: "/var/log/syslog"
  - name: "Nginx Access Log"
    path: "/var/log/nginx/access.log"
  - name: "Nginx Error Log"
    path: "/var/log/nginx/error.log"
